config/routes.rb
Dpcrm::Application.routes.draw do
  

  resources :companies do
    resources :contacts
    member do
      get 'test_member'
    end
    collection do
      get 'copy'
    end
  end
  
    resources :contacts

  
  root 'companies#index'
  
  
  

  

end

app/models/company.rb
class Company < ActiveRecord::Base
  validates_presence_of :name, :email, :phone
  validates_uniqueness_of :name
  has_many :contacts
  
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates_presence_of :last_name
  belongs_to :company
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  
  def index
    @companies = Company.all
  end
  
  def new
    @company = Company.new
    if(params[:copy_company])
      @copy_company = Company.find(params[:copy_company])
      @company = @copy_company.dup
      @company.name = ''
    end
  end
  
  def create
        
    @company = Company.new(company_params)
            if @company.save
              redirect_to company_path(@company)
            else
              render :action => 'new'
            end
    
    
  end
  
  def show
    @company = Company.find(params[:id])
  end
  
  def edit
    @company = Company.find(params[:id])
  end
  
  def update
    @company = Company.find(params[:id])
    @company.update(company_params)
    if @company.save
      redirect_to company_path(@company)
    else
      render :action => 'new'
    end
  end
  
  def destroy
    @company = Company.find(params[:id])
    @company.destroy
    redirect_to companies_path
  end
  
  def copy
    @companies = Company.all.select('name, id')
  end
  
  def test_member
    render :text => params[:id].to_s
  end
  
  private
  
  def company_params
    params.require(:company).permit(:name, :tags, :assigned_to, :email, :website, :phone, :mobile_phone, :fax, :address1, :address2, :city, :state, :zip, :comments, :support_package, :default => 'Gold')
  end
  
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
before_filter :set_contact, :only => [:show, :edit, :update, :destroy]
  
  def index
   if params[:company_id]
      @contacts = Contact.where(:company_id => params[:company_id])
      @company = Company.find(params[:company_id])
   else
     @contacts = Contact.all
   end
  end
  
  def show
    if params[:company_id]
      @company = Company.find(params[:company_id])
    end
  end
  
  def new
    @contact = Contact.new
    if params[:company_id]
      @company = Company.find(params[:company_id])
      # dealing with contacts added with company
    else
      @companies = Company.all.order("name")
      #dealing with contacts added independently
    end
  end
  
  def create
    @contact = Contact.new(contact_params)
    
    if @contact.save
        if params[:company_id]
          redirect_to company_contacts_path
        else
          redirect_to contacts_path
        end
    else
        if params[:company_id]
          redirect_to new_company_contact_path
          flash[:notice] = @contact.errors.full_messages
        else
          redirect_to new_contact_path
          flash[:notice] = @contact.errors.full_messages
        end
          #render :action => 'new', :locals => {:company_id => params[:company_id]}
      
      
    end
    
    
    
   
  end
  
  def edit
    if params[:company_id]
      @company = Company.find(params[:company_id])
      # dealing with contacts added with company
    else
      @companies = Company.all.order("name")
      #dealing with contacts added independently
    end
  end
  
  def update
    @contact.update(contact_params)
    @contact.save
    if @contact.save
        if params[:company_id]
          redirect_to company_contacts_path
        else
          redirect_to contacts_path
        end
    else
        if params[:company_id]
          redirect_to new_company_contact_path
          flash[:notice] = @contact.errors.full_messages
        else
          redirect_to new_contact_path
          flash[:notice] = @contact.errors.full_messages
        end
          #render :action => 'new', :locals => {:company_id => params[:company_id]}
      
      
    end
    
  end
  
  def destroy
    #render :text => params
    @contact.destroy
        if params[:company_id]
          redirect_to company_contacts_path
          flash[:notice] = 'Contact Deleted'
        else
          redirect_to contacts_path
          flash[:notice] = 'Contact Deleted'
        end 
  end
  
private

def set_contact
  @contact = Contact.find(params[:id])
end

def contact_params
  params.require(:contact).permit(:first_name, :last_name, :company_id, :tags, :assigned_to, :title, :email, :phone, :mobile_phone, :address1, :address2, :city, :state, :zip, :comments, :conference, :support_package)
end  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/companies/_form.html.erb
<%@company.errors.full_messages.each do |e|%>
	<div style='color:red'><%=e%></div>
<%end%>

<%=form_for @company do |f|%>
<div class = 'row'>
	<div class = 'span12'>
	<div class = 'row'>
			<div class = 'span3'>
				<p>Name</p>
				<%=f.text_field :name, :size=>25, :maxlength => 25%>
			</div>
			
			<div class = 'span3'>
				<p>Tags</p>
				<%=f.text_field :tags%>
			</div>
			
			<div class = 'span3'>
				<p>Assigned To</p>
				<%=f.text_field :assigned_to%>
			</div>
			
			<div class = 'span3'>
				<p>Email</p>
				<%=f.text_field :email%>	
			</div>
			
	</div>
	
	<div class = 'row'>
		<ul>  </ul>
		<ul>  </ul>
	</div>
	
	<div class = 'row'>
		
			<div class = 'span3'>
				<p>Website</p>
				<%=f.text_field :website%>
			</div>
			
			<div class = 'span3'>
				<p>Phone</p>
				<%=f.text_field :phone%>
			</div>
			
			<div class = 'span3'>
				<p>Mobile Phone</p>
				<%=f.text_field :mobile_phone%>
			</div>
			
			<div class = 'span3'>
				<p>Fax</p>
				<%=f.text_field :fax%>
			</div>
			
		
	</div>
	
	<div class = 'row'>
		<ul>  </ul>
		<ul>  </ul>
	</div>
	
	<div class = 'row'>
		
			<div class = 'span3'>
				<p>Address 1</p>
				<%=f.text_field :address1%>
			</div>
			
			<div class = 'span3'>
				<p>Address 2</p>
				<%=f.text_field :address2%>
			</div>
			
			<div class = 'span3'>
				<p>City</p>
				<%=f.text_field :city%>
			</div>
			
			<div class = 'span3'>
				<p>State</p>
				<%=f.text_field :state, :value => 'FL'%>
			</div>
			
		
	</div>
	
	<div class = 'row'>
		<ul>  </ul>
		<ul>  </ul>
	</div>
	
	<div class = 'row'>
		
			<div class = 'span3'>
				<p>Zip</p>
				<%=f.text_field :zip%>
			</div>
			
			<div class = 'span3'>
				<p>Support Package</p>
				<%=f.text_field :support_package%> </br>
			</div>
			
	</div>

	<div class = "row">
		<div class = 'span8'>
			<p>Comments</p>
			<%=f.text_area :comments, :cols => 500, :rows => 5, :style => 'width: 500px' %>
		</div>
	</div>
	</div>
			
</div>



<%=f.submit%>
<%end%>

app/views/companies/copy.html.erb
<h2> Select Company to Copy From </h2>
<form action="/companies/new" method='get'>
	<%=select_tag 'copy_company', options_for_select(@companies.collect{|c|[c.name, c.id]})%>
	<%=button_to 'Continue', '/companies/new'%>
</form>

app/views/companies/edit.html.erb
<h1> Edit Company </h1>

<%=render 'form'%>

<%=link_to 'Cancel', company_path(@company)%>

app/views/companies/index.html.erb
<h2> List of Companies </h2>

<%@companies.each do |c|%>
	<div class = 'row'>
	<div class = 'span3'>
		<p> <%=link_to c.name, company_path(c)%> </br> </p>
	</div>
	<div class = 'span9'>
		<p> <%=c.comments%> </br> </p>
	</div>
	</div>
	
<%end%>

<%=link_to "Create a Company", new_company_path, :class => 'btn btn-mini btn-primary'%>

app/views/companies/new.html.erb
<h1> Add a new Company </h1>
<%=link_to "Copy from Another Company", "/companies/copy"%>
<%=render 'form'%>

<%=link_to "Back to Companies", root_path, :class => 'btn btn-primary'%>

app/views/companies/show.html.erb
<h2> Company Information </h2>

<div class = 'row'>
	
	<div class = 'span12'>

	<div class = 'row'>
		
			<div class = 'span3'>
				<ul><b>Name </b></ul>
				<ul><%=@company.name%></ul>
			</div>
			
			<div class = 'span3'>
				<ul><b>Tags </b></ul>
				<ul><%=@company.tags%></ul>
			</div>
			
			<div class = 'span3'>
				<ul><b>Assigned To </b></ul>
				<ul><%=@company.assigned_to%></ul>		
			</div>
			
			<div class = 'span3'>
				
				<ul><b>Email </b></ul>
				<ul><%=@company.email%></ul>
				
			</div>
			
	</div>
	
	<div class = 'row'>
		<ul>  </ul>
		<ul>  </ul>
	</div>
	
	<div class = 'row'>
		
			<div class = 'span3'>
				<ul><b>Website</b> </ul>
				<ul><%=@company.website%> </ul>
			</div>
			
			<div class = 'span3'>
				<ul><b>Phone </b></ul>
				<ul><%=@company.phone%></ul>
			</div>
			
			<div class = 'span3'>
				<ul><b>Mobile Phone </b> </ul>
				<ul><%=@company.mobile_phone%> </ul>
			</div>
			
			<div class = 'span3'>
				<ul><b>Fax </b></ul>
				<ul><%=@company.fax%></ul>
			</div>
			
		
	</div>
	
	<div class = 'row'>
		<ul>  </ul>
		<ul>  </ul>
	</div>
	
	<div class = 'row'>
		
			<div class = 'span3'>
				<ul><b>Address 1 </b></ul>
				<ul><%=@company.address1%> </ul>
			</div>
			
			<div class = 'span3'>
				<ul><b>Address 2 </b></ul>
				<ul><%=@company.address2%></ul>
			</div>
			
			<div class = 'span3'>
				<ul><b>City </b></ul>
				<ul><%=@company.city%> </ul>
			</div>
			
			<div class = 'span3'>
				<ul><b>State </b></ul>
				<ul><%=@company.state%> </ul>
			</div>
			
		
	</div>
	
	<div class = 'row'>
		<ul>  </ul>
		<ul>  </ul>
	</div>
	
	<div class = 'row'>
		
			<div class = 'span3'>
				<ul><b>Zip </b></ul>
				<ul><%=@company.zip%></ul>
			</div>
			
			<div class = 'span3'>
				<ul><b>Support Package </b> </ul>
				<ul><%=@company.support_package%> </ul>
			</div>
			
	</div>

	<div class = "row">
		<div class = 'span8'>
			<ul><b>Comments </b></ul>
			<ul><%=@company.comments%></ul>
		</div>
	</div>
	</div>
			
</div>

	
	<div class = 'row'>
			<div class = 'span6'>
				<%=link_to "Back to List of Companies", companies_path, :class => 'btn btn-primary btn-mini'%>
				<%=link_to "Edit Company", edit_company_path(@company), :class => 'btn btn-primary btn-mini'%>
				<%= link_to "Delete Company", "/companies/#{@company.id}", :method => 'delete', :class => 'btn btn-primary btn-mini'%>
				<%=link_to "View Contacts", company_contacts_path(:company_id => params[:id]), :class => 'btn btn-primary btn-mini'%>
			</div>
	</div>

app/views/contacts/_form.html.erb
<%=simple_form_for (@contact) do |f| %><div class = 'row'>
	<div class = 'span12'>
	<div class = 'row'>
			<div class = 'span3'>
				<%=f.input :first_name %>
			</div>
			
			<div class = 'span3'>
    			<%=f.input :last_name %>
			</div>
			
			<div class = 'span3'>
				<%=f.input :tags %>
			</div>
			
			<div class = 'span3'>
				<%=f.input :assigned_to %>
			</div>
			
	</div>
	
	<div class = 'row'>
		<ul>  </ul>
		<ul>  </ul>
	</div>
	
	<div class = 'row'>
		
			<div class = 'span3'>
				<%=f.input :title %>
			</div>
			
			<div class = 'span3'>
				<%=f.input :email %>
			</div>
			
			<div class = 'span3'>
				 <%=f.input :phone %>
			</div>
			
			<div class = 'span3'>
				<%=f.input :mobile_phone %>
			</div>
			
		
	</div>
	
	<div class = 'row'>
		<ul>  </ul>
		<ul>  </ul>
	</div>
	
	<div class = 'row'>
		
			<div class = 'span3'>
				<%=f.input :address1 %>
			</div>
			
			<div class = 'span3'>
				<%=f.input :address2 %>
			</div>
			
			<div class = 'span3'>
				<%=f.input :city %>
			</div>
			
			<div class = 'span3'>
				<%=f.input :state %>
			</div>
			
		
	</div>
	
	<div class = 'row'>
		<ul>  </ul>
		<ul>  </ul>
	</div>
	
	<div class = 'row'>
		
			<div class = 'span3'>
				 <%=f.input :zip %>
			</div>
			
			<div class = 'span3'>
				<%=f.input :conference %>
			</div>
			
			<div class = 'span3'>
				<%=f.input :support_package %>
			</div>
			
	</div>

	<div class = "row">
		<div class = 'span8'>
			<%=f.input :comments, :input_html => { :cols => 700, :rows => 5 } %>
		</div>
	</div>
	</div>
			
</div>

    <%=f.input :company_id, :as => :hidden, :input_html => { :value => params[:id] }%>

<%=f.submit%>

    
<%end%>

app/views/contacts/_form_company_contact.html.erb
<%=simple_form_for @contact, :url => company_contacts_path(@company, @contact), :method => :post do |f| %>
			<div class = 'row'>
			<div class = 'span12'>
			<div class = 'row'>
					<div class = 'span3'>
						<%=f.input :first_name %>
					</div>
					
					<div class = 'span3'>
		    			<%=f.input :last_name %>
					</div>
					
					<div class = 'span3'>
						<%=f.input :tags %>
					</div>
					
					<div class = 'span3'>
						<%=f.input :assigned_to %>
					</div>
					
			</div>
			
			<div class = 'row'>
				<ul>  </ul>
				<ul>  </ul>
			</div>
			
			<div class = 'row'>
				
					<div class = 'span3'>
						<%=f.input :title %>
					</div>
					
					<div class = 'span3'>
						<%=f.input :email %>
					</div>
					
					<div class = 'span3'>
						 <%=f.input :phone %>
					</div>
					
					<div class = 'span3'>
						<%=f.input :mobile_phone %>
					</div>
					
				
			</div>
			
			<div class = 'row'>
				<ul>  </ul>
				<ul>  </ul>
			</div>
			
			<div class = 'row'>
				
					<div class = 'span3'>
						<%=f.input :address1 %>
					</div>
					
					<div class = 'span3'>
						<%=f.input :address2 %>
					</div>
					
					<div class = 'span3'>
						<%=f.input :city %>
					</div>
					
					<div class = 'span3'>
						<%=f.input :state %>
					</div>
					
				
			</div>
			
			<div class = 'row'>
				<ul>  </ul>
				<ul>  </ul>
			</div>
			
			<div class = 'row'>
				
					<div class = 'span3'>
						 <%=f.input :zip %>
					</div>
					
					<div class = 'span3'>
						<%=f.input :conference %>
					</div>
					
					<div class = 'span3'>
						<%=f.input :support_package, :collection => ["GOLD", "SILVER", "BRONZE"], :selected => "GOLD" %>
					</div>
					
			</div>
		
			<div class = "row">
				<div class = 'span8'>
					<%=f.input :comments, :input_html => { :cols => 700, :rows => 5, :style => 'width: 500px' } %>
				</div>
			</div>
			</div>
			
	</div>
<%=f.input :company_id, :as => :hidden, :input_html => { :value => params[:company_id] }%>

<%=f.submit%>

    
<%end%>

app/views/contacts/_form_contact.html.erb
	<%=simple_form_for (@contact) do |f| %>
			<div class = 'row'>
			<div class = 'span12'>
			<div class = 'row'>
					<div class = 'span3'>
						<%=f.input :first_name %>
					</div>
					
					<div class = 'span3'>
		    			<%=f.input :last_name %>
					</div>
					
					<div class = 'span3'>
						<%=f.input :tags %>
					</div>
					
					<div class = 'span3'>
						<%=f.input :assigned_to %>
					</div>
					
			</div>
			
			<div class = 'row'>
				<ul>  </ul>
				<ul>  </ul>
			</div>
			
			<div class = 'row'>
				
					<div class = 'span3'>
						<%=f.input :title %>
					</div>
					
					<div class = 'span3'>
						<%=f.input :email %>
					</div>
					
					<div class = 'span3'>
						 <%=f.input :phone %>
					</div>
					
					<div class = 'span3'>
						<%=f.input :mobile_phone %>
					</div>
					
				
			</div>
			
			<div class = 'row'>
				<ul>  </ul>
				<ul>  </ul>
			</div>
			
			<div class = 'row'>
				
					<div class = 'span3'>
						<%=f.input :address1 %>
					</div>
					
					<div class = 'span3'>
						<%=f.input :address2 %>
					</div>
					
					<div class = 'span3'>
						<%=f.input :city %>
					</div>
					
					<div class = 'span3'>
						<%=f.input :state %>
					</div>
					
				
			</div>
			
			<div class = 'row'>
				<ul>  </ul>
				<ul>  </ul>
			</div>
			
			<div class = 'row'>
				
					<div class = 'span3'>
						 <%=f.input :zip %>
					</div>
					
					<div class = 'span3'>
						<%=f.input :conference %>
					</div>
					
					<div class = 'span3'>
						<%=f.input :support_package %>
					</div>
					
			</div>
		
			<div class = "row">
				<div class = 'span8'>
					<%=f.input :comments, :input_html => { :cols => 700, :rows => 5, :style => 'width: 500px' } %>
				</div>
			</div>
</div>
			
	</div>

	<label>Select a Company</label>
	<%=f.select 'company_id', options_for_select(@companies.collect{|c|[c.name, c.id]}), :include_blank => "Please Select" %>

	<%=f.submit%>

    
<%end%>

app/views/contacts/_form_fields.html.erb
<div class = 'row'>
	<div class = 'span12'>
	<div class = 'row'>
			<div class = 'span3'>
				<%=f.input :first_name %>
			</div>
			
			<div class = 'span3'>
    			<%=f.input :last_name %>
			</div>
			
			<div class = 'span3'>
				<%=f.input :tags %>
			</div>
			
			<div class = 'span3'>
				<%=f.input :assigned_to %>
			</div>
			
	</div>
	
	<div class = 'row'>
		<ul>  </ul>
		<ul>  </ul>
	</div>
	
	<div class = 'row'>
		
			<div class = 'span3'>
				<%=f.input :title %>
			</div>
			
			<div class = 'span3'>
				<%=f.input :email %>
			</div>
			
			<div class = 'span3'>
				 <%=f.input :phone %>
			</div>
			
			<div class = 'span3'>
				<%=f.input :mobile_phone %>
			</div>
			
		
	</div>
	
	<div class = 'row'>
		<ul>  </ul>
		<ul>  </ul>
	</div>
	
	<div class = 'row'>
		
			<div class = 'span3'>
				<%=f.input :address1 %>
			</div>
			
			<div class = 'span3'>
				<%=f.input :address2 %>
			</div>
			
			<div class = 'span3'>
				<%=f.input :city %>
			</div>
			
			<div class = 'span3'>
				<%=f.input :state %>
			</div>
			
		
	</div>
	
	<div class = 'row'>
		<ul>  </ul>
		<ul>  </ul>
	</div>
	
	<div class = 'row'>
		
			<div class = 'span3'>
				 <%=f.input :zip %>
			</div>
			
			<div class = 'span3'>
				<%=f.input :conference %>
			</div>
			
			<div class = 'span3'>
				<%=f.input :support_package %>
			</div>
			
	</div>

	<div class = "row">
		<div class = 'span8'>
			<%=f.input :comments, :input_html => { :cols => 700, :rows => 5, :style => 'width: 500px' } %>
		</div>
	</div>
	</div>
			
</div>

app/views/contacts/edit.html.erb
<h2>Edit a contact</h2>

<%if params[:company_id]%>
	<%=render 'form_company_contact'%>
<%else%>
	<%=render 'form_contact'%>
<%end%>

<%=link_to 'Cancel', contacts_path, :class => 'btn btn-primary btn-mini'%>

app/views/contacts/index.html.erb
<h2> List of Contacts 
	<%if params[:company_id]%>
		for <%=@company.name%>
	<%end%>
	</h2>
		
	

<div class = 'row'>
	<div class = 'span2'>
		<b>Last Name</b>
	</div>
	
	<div class = 'span2'>
		<b>First Name</b>
	</div>
	
	<div class = 'span2'>
		<b>Phone </b>
	</div>
	
	<div class = 'span6'>
		<b>Comments </b>
	</div>
	
</div>

<%@contacts.each do |c|%>
<div class = 'row'>
	
	<div class = 'span2'>
		<%if params[:company_id]%>
			<%=link_to c.last_name, "/companies/#{@company.id}/contacts/#{c.id}"%>
		<%else%>
			<%=link_to c.last_name, "/contacts/#{c.id}"%>
		<%end%>
	</div>
	
	<div class = 'span2'>
		<%=c.first_name%>
	</div>
	
	<div class = 'span2'>
		<%=c.phone%></p>
	</div>
	
	<div class = 'span6'>
		<%=c.comments%></p>
	</div>

</div>


<%end%>

<%if params[:company_id]%>
	<%=link_to 'Add a new Contact', new_company_contact_path, :class => 'btn btn-mini btn-primary'%>
	<%=link_to 'Return to Company Info', company_path(@company), :class => 'btn btn-mini btn-primary'%>
<%else%>
	<%=link_to 'Add a new Contact', new_contact_path, :class => 'btn btn-mini btn-primary'%>
<%end%>

app/views/contacts/new.html.erb
<h2>Add a contact</h2>

<%if params[:company_id]%>
	<%=render 'form_company_contact'%>
	<%=link_to 'Cancel', company_contacts_path, :class => 'btn btn-primary btn-mini'%>
<%else%>
	<%=render 'form_contact'%>
	<%=link_to 'Cancel', contacts_path, :class => 'btn btn-primary btn-mini'%>
<%end%>

app/views/contacts/show.html.erb
<h2> Contact Details </h2>

<div class = 'row-fluid'>
	
	<div class = 'span3'>
		
				<ul>First Name: </ul>
				<ul>Last Name: </ul>
				<ul>Tags: </ul>
				<ul>Assigned To: </ul>
				<ul>Title: </ul>
				<ul>Email: </ul>
				<ul>Phone: </ul>
				<ul>Mobile Phone: </ul>
				<ul>Address 1: </ul>
				<ul>Address 2: </ul>
				<ul>City: </ul>
				<ul>State: </ul>
				<ul>Zip: </ul>
				<ul>Comments: </ul>
				<ul>Conference: </ul>
				<ul>Support Package: </ul>
	</div>
	
	<div class = 'span4'>
	
	<ul><%=@contact.first_name %></br></ul>
    <ul><%=@contact.last_name %></br></ul>
    <ul><%=@contact.tags %></br></ul>
    <ul><%=@contact.assigned_to %></br></ul>
    <ul><%=@contact.title %></br></ul>
    <ul><%=@contact.email %></br></ul>
    <ul><%=@contact.phone %></br></ul>
    <ul><%=@contact.mobile_phone %></br></ul>
    <ul><%=@contact.address1 %></br></ul>
    <ul><%=@contact.address2 %></br></ul>
    <ul><%=@contact.city %></br></ul>
    <ul><%=@contact.state %></br></ul>
    <ul><%=@contact.zip %></br></ul>
    <ul><%=@contact.comments %></br></ul>
    <ul><%=@contact.conference %></br></ul>
    <ul><%=@contact.support_package %></br></ul>
	
	</div>
	
	
</div>



<%if params[:company_id]%>
		<%=link_to "Back to Contacts", company_contacts_path, :class => 'btn btn-mini btn-primary'%>
		<%=link_to "Edit Contact", edit_company_contact_path(@company, @contact), :class => 'btn btn-mini btn-primary'%>
		<%=link_to "Delete Contact", company_contact_path(@company, @contact), method: :delete, data: {confirm: 'Are you sure?'}, :class => 'btn btn-mini btn-primary'%>
<%else%>
		<%=link_to "Back to Contacts", contacts_path, :class => 'btn btn-mini btn-primary'%>
		<%=link_to 'Edit Contact', edit_contact_path(@contact), :class => 'btn btn-mini btn-primary'%>
		<%=link_to "Delete Contact", contact_path(@contact), method: :delete, data: {confirm: 'Are you sure?'}, :class => 'btn btn-mini btn-primary'%>
<%end%>

app/views/layouts/_header.html.erb
    <div class="navbar">
    <div class="navbar-inner">
    <div class="container">
     
    <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    </a>
     
    <!-- Be sure to leave the brand out there if you want it shown -->
    <a class="brand" href="#">DP CRM</a>
     
    <!-- Everything you want hidden at 940px or less, place within here -->
    <div class="nav-collapse">
                    <ul class="nav">
                        <li>
                            <%= link_to 'Home',  root_path %>
                        </li>
                        <li>    
                            <%= link_to 'Companies',  companies_path %>
                        </li>
                        <li>    
                            <%= link_to 'Contacts',  contacts_path %>
                        </li>
                    </ul>
                    <ul class="nav pull-right">
                                <li><%= link_to 'Login',  '#' %></li>
                    </ul>
                </div>
     
    </div>
    </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dpcrm</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class = 'container'>
	
	<%=render '/layouts/header'%>
	<%if flash[:notice]%>
		<%=flash[:notice]%>
	<%end%>
	
	<%= yield %>
</div>

</body>
</html>